# Generated by Django 6.1.1 on 2026-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=None, help_text='Optional. Leave blank to auto-allow duplicates without SKU.', max_length=120, null=True, unique=True),
        ),
    ]
